### ISSUE TITLE
request: Paginated embeds with embed-jsx

### ISSUE THREAD

**Issue by PyroTechniac** [sapphiredev/utilities#109]
**Is your feature request related to a problem? Please describe.**
Creating embeds with embed-jsx is nice, however with the util in discord.js-utilities, it is possible to create paginated embeds, which I would like to do with jsx syntax

**Describe the solution you'd like**
Using Fragment syntax, it should be possible to create paginated embeds with the tsconfig option `jsxFragmentFactory`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Favna** [comment]
Closing because @PyroTechniac is pretty much the only one to also maintain that and this has gone stale. Feel free to request to a re-open if needed.
