### ISSUE TITLE
bug: Snowflake generating the same ID twice before incrementing

### ISSUE THREAD

**Issue by TheStyxo** [sapphiredev/utilities#154]
**Describe the bug**

![image](https://user-images.githubusercontent.com/63962807/129935036-7b313b99-3baa-49dc-ade1-3032c6022357.png)
![image](https://user-images.githubusercontent.com/63962807/129935881-e638e9d2-9e90-49da-918a-6a49e315c19b.png)

Here's how I generated the IDs
```ts
   public static readonly snowflake = new Snowflake(new Date('2005-08-07T00:00:00.000Z'));
   /**
     * Generate a buttonID for discord
     * Looks like loop-q:a:n-2132321332112
     * @param command The name of the command to run
     * @param args The arguments to pass the command
     */
    public static generateButtonID(command: string, args?: string[]): string {
        const test = `${command}-${args ? args.join(':') : 'null'}-${this.snowflake.generate()}`;
        console.log(test);
        return test;
    };
```
**To Reproduce**

1. Running the Snowflake#generate() method I guess?

**Comment by Favna** [comment]
@vladfrangu

**Comment by TheStyxo** [comment]
Also, this happened when I switched to the latest Node version instead of LTS...

**Comment by Favna** [comment]
@TheStyxo can you create a repro of this using something like https://runkit.com, https://codesandbox.io/ or a small GitHub repository?

**Comment by TheStyxo** [comment]
Hey I made a replit repo for testing this, https://replit.com/join/oqgbhlizmt-parasdeshpande

**Comment by TheStyxo** [comment]
> Of the issue you're having. Snowflake doesn't have to be used in the context of a Discord bot so if you can reproduce it outside of one that'd be best. Especially because it's much easier to run a simple REPL query than to run a whole Discord bot. Hence why I suggested runkit and codesandbox.

https://replit.com/join/oqgbhlizmt-parasdeshpande

**Comment by TheStyxo** [comment]
![image](https://user-images.githubusercontent.com/63962807/131467795-0aef79c9-7f62-4b05-b0d5-cfdc322b79d0.png)

**Comment by TheStyxo** [comment]
@Favna any updates? I'm currently adding a random string at the end as a temporary fix...

**Comment by Favna** [comment]
I've been on vacation so I haven't looked yet
