### ISSUE TITLE
bug: paginated + ephemeral + double command = bot crashes

### ISSUE THREAD

**Issue by HugoFerrant** [sapphiredev/utilities#370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Bot crash (sapphire error so the whole bot crashes) when using a paginated message in ephemeral mode and sending a command twice.

### Steps To Reproduce

1. Create a chatInput command with a paginated message with at least 2 pages (the pages buttons/select are needed)
2. Make paginated-message's interaction ephemeral (`interaction.deferReply({ ephemeral: true })`)
3. use the command twice without "Stopping" the first one. Just use the command twice in a row without doing anything else
4. Bot crashes

### Expected behavior

Either disable usage of paginated + ephemeral, or fix the crash issue

### Additional context

The error in the logs is the famous `DiscordAPIError: Unknown Message`. I guess because the lib is trying to load the previous message to remove the buttons&select (that's what it does when no ephemeral), but since it's an ephemeral interaction, it can't find it.

**Comment by HugoFerrant** [comment]
as I'm a nice pal is a repro repo : https://github.com/HugoFerrant/repro-paginated-ephemeral

**Comment by favna** [comment]
Released in v4.11.1

**Comment by HugoFerrant** [comment]
you rock @favna !
