### ISSUE TITLE
request: add components for MessagePrompter

### ISSUE THREAD

**Issue by noftaly** [sapphiredev/utilities#432]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

I would be great if there was a way to use components (buttons/select menus) for MessagePrompter, for example for the confirm (yes/no) prompt, or any custom component prompt (the same way there is a custom reaction prompt)

### Desired solution

It could just replace the replace the current confirm entirely, or add the `component-confirm` and `components` strategies, for respectively having a yes/no button and having custom components.
If you decide to go with the latter, perhaps `confirm` should be renamed to `reaction-confirm` for symmetry.

### Alternatives considered

Not using interactions, or making a manual prompter

**Comment by favna** [comment]
I'm going to reject because it's extremely easy to do manually and adding it to MessagePrompter would mean completely overhauling the code to support components which is way more work than that.

**Prompting for Yes/No using Buttons**

```ts
import { inlineCode } from '@discordjs/builders';
import { Command } from '@sapphire/framework';
import { Time } from '@sapphire/time-utilities';
import { MessageActionRow, MessageButton } from 'discord.js';

// etc
  public override async messageRun(message: Message) {
    const yesButton = new MessageButton() //
      .setCustomId('yes_button')
      .setEmoji('✅')
      .setStyle('PRIMARY')
      .setLabel('Yes');

    const noButton = new MessageButton() //
      .setCustomId('no_button')
      .setEmoji('❌')
      .setStyle('DANGER')
      .setLabel('No');

    const buttonsRow = new MessageActionRow() //
      .setComponents([yesButton, noButton]);

    const myMessage = await message.channel!.send({ content: 'Please choose', components: [buttonsRow] });

    const clicks = await myMessage.awaitMessageComponent({
      componentType: 'BUTTON',
      time: Time.Second * 10,
      filter: (buttonInteraction) =>
        buttonInteraction.user.id === message.author.id &&
        (buttonInteraction.customId === 'yes_button' || buttonInteraction.customId === 'no_button')
    });

    return clicks.reply({
      content: `Button ${inlineCode('clicks.customId')} was clicked!`
    });
  }
```
