### ISSUE TITLE
request: ability to import single functions in `@sapphire/utilities`

### ISSUE THREAD

**Issue by kyranet** [sapphiredev/utilities#452]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

Right now, if we want to import an utility, we have to import from `@sapphire/utilities`, which loads all of the utilities, which in turn increases the load time and memory usage.

### Desired solution

Be able to import with subpaths, e.g. `import { chunk } from '@sapphire/utilities/chunk';`

### Alternatives considered

N/a.

**Comment by favna** [comment]
This is a good idea but I have no idea how to setup the build tooling for this. `tsup` generates single files for IIFE, CJS and ESM but now we want multiple files for CJS and ESM. Then we also need to adjust the `exports` array in the `package.json` which will make that very complex, possible, but complex.

**Comment by imranbarbhuiya** [comment]
ig setting `bundle: false` will generate separate files. Also set `legacy-output` so we'll get all the `esm` output in `esm` folder, `cjs` in root and `iife` in `iife` folder.
