### ISSUE TITLE
request: add `tryParseURL` to utilities + rename `tryParse` to `tryParseJSON` and add deprecation notice to the former of those two.

### ISSUE THREAD

**Issue by favna** [sapphiredev/utilities#481]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

We have a `tryParse` in /utilities which wraps `JSON.parse` in a try/catch. Another case where you may want to parse and catch is `new URL(...)` so lets introduce `tryParseURL`

### Desired solution

- Implement new file
- Do something smart for handling the type of `URL`. We cannot rely on people having DOM in their lib. Probably a triple slash directive.
- Add new unit tests
- Rename `tryParse` to `tryParseJSON`
- Add an alias for `tryParseJSON` with `@deprecated` a TSDoc comment
- Add the alias to the aliases map for subpath exports
- Run `check-subpath` in `packages/utilities` to update the package.json

```ts
/**
 * Tries parse a string to a {@link URL} object
 * @param value The possible URL to parse
 * @returns an URL object if it was a valid URL or `null` if it was not.
 */
export function tryParseURL(value: string): URL | null {
  try {
    return new URL(value);
  } catch {
    return null;
  }
}
```

### Alternatives considered

Not implementing it? Jk

**Comment by legendhimslef** [comment]
I am working on it.
