### ISSUE TITLE
bug: [@sapphire/ts-config] Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5.

### ISSUE THREAD

**Issue by nikolaischunk** [sapphiredev/utilities#566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

When extending `@sapphire/ts-config` in the tsconfig, the following error shows up

![grafik](https://user-images.githubusercontent.com/58025175/225774006-214cd373-33ac-4604-a512-93d8e2170fc3.png)
![grafik](https://user-images.githubusercontent.com/58025175/225774046-20c7aadd-4e9f-4b97-8cdd-9d447894701e.png)

the `importsNotUsedAsValues` option seems deprecated, and should be updated in this package

### Steps To Reproduce

Extend `@sapphire/ts-config` in your `tsconfig`

### Expected behavior

No error should be shown

### Additional context

https://github.com/microsoft/TypeScript/issues/51909
Found this (related?) Issue on the topic

**Comment by favna** [comment]
It should be noted that Sapphire is not updated for TS 5.x yet, and when it does this package in particular will receive a major version bump.

**Comment by nikolaischunk** [comment]
So the solution, for now, is, to not use TS 5?

**Comment by favna** [comment]
Correct

**Comment by favna** [comment]
For now you can add `"ignoreDeprecations": "5.0"` to your tsconfig, if the rest works when you do that. TS 5.x compatibility will be added in due course whenever everything builds and is tested to work with it. Generally however you never want to rush those things so let that be a lesson for the future I guess.

**Comment by favna** [comment]
That said, as we are aware of TS 5.x I'm going to pre-emptively close this issue. Once we ship TS 5.x compatibility it will be announced on the Sapphire discord server. You can also track #567 for updates.
