### ISSUE TITLE
bug: deepClone cannot handle buffers

### ISSUE THREAD

**Issue by Lioness100** [sapphiredev/utilities#591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

`deepClone` throws when handling a Buffer.

### Steps To Reproduce

```ts
deepClone(Buffer.from([0x62, 0x75, 0x66, 0x66, 0x65, 0x72]));
```

Throws:
TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined

Stack trace:
https://github.com/sapphiredev/utilities/blob/main/packages/utilities/src/lib/deepClone.ts#L50

Does this not handle any constructors that throw errors if arguments aren't given?

### Expected behavior

It returns `Buffer.from([0x62, 0x75, 0x66, 0x66, 0x65, 0x72])`

**Comment by favna** [comment]
hm. deepClone was never written to also support buffers.
