### ISSUE TITLE
request: Is there a reason for sapphire/event-iterator?

### ISSUE THREAD

**Issue by jacoobes** [sapphiredev/utilities#613]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

An native way already exists 
https://nodejs.org/api/events.html#eventsonemitter-eventname-options

At best, this could be a polyfill for really old node versions

### Desired solution

Audit package

### Alternatives considered

n/a

**Comment by kyranet** [comment]
While a native way already exists, it doesn't have support for filtering.
