### ISSUE TITLE
bug: bun build `@sapphire/utilities`

### ISSUE THREAD

**Issue by mthsmb** [sapphiredev/utilities#702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Warning `bun build` due wildcard sideEffects in `@sapphire/utilities`

### Steps To Reproduce

Execute `bun build --target node src/index.ts --outdir dist/` in any project using `bun build --target node src/index.ts --outdir dist/`

### Expected behavior

Use explicit sideEffects so the build is optimized and the warning doesn't appear

### Screenshots

![image](https://github.com/sapphiredev/utilities/assets/13896395/a2448242-4444-48ea-8acc-7ea6ec688020)

**Comment by favna** [comment]
Urgh thanks for the report. We'll have to do this as a prepack script because the sideEffects are dynamically generated by tsup. I'll get on this.

**Comment by favna** [comment]
Released in v3.15.2
