### ISSUE TITLE
request(discord.js-utilities): make it possible to parse MessagePrompter results

### ISSUE THREAD

**Issue by noftaly** [sapphiredev/utilities#92]
**Is your feature request related to a problem? Please describe.**

Using a MessagePrompter with a MessageStrategy is used in most of the cases to ask for arguments, but in a separate message. But it currently only returns a Message, so if we asked for a channel, we have to parse it ourselves. This makes it redundant as the same logic is already present in the library, to parse command arguments for example.

**Describe the solution you'd like**

There should be a way to parse MessagePrompter results, either through the `Args` class (which will require quite a lot of refactor since it currently requires a command, but a MessagePrompter can be run anywhere, including in an event), or with another custom ""type parser"" that can also be implemented in `Args` to avoid duplicating the same logic twice.

**Describe alternatives you've considered**

Parse it myself, not optimal. And making our own instance of `Args` is not possible because as I said, it requires a command ; but MessagePrompter can be used in an event.

**Comment by Nytelife26** [comment]
This is certainly interesting - and I must ask, what's stopping you from running the chosen argument type's parse function on the returned message content instead of trying to instance `Args`?

**Comment by noftaly** [comment]
> what's stopping you from running the chosen argument type's parse function on the returned message content instead of trying to instance Args?

Do you mean using `CoreArguments`? https://github.com/sapphire-project/framework/tree/main/src/arguments
I might be wrong but I don't think they are exported, at least I did not find them in the exports; and VSCode do not propose them to me.

**Comment by Nytelife26** [comment]
> Do you mean using `CoreArguments`?

Not specifically, you can use any argument a bot has loaded into the arguments store I believe, so long as the arguments are loaded before whatever you're trying to do.

**Comment by noftaly** [comment]
Yes you're right, I could use the injected context.
It is fairly easy to use so I don't know if it is necessary fo MessagePrompter to have its own implementation, so I'll let the maintainers choose whether or not close this issue.

**Comment by Nytelife26** [comment]
> It is fairly easy to use so I don't know if it is necessary for MessagePrompter to have its own implementation

I do still believe that this might be a good opportunity to propose a corollary suggestion of making args able to work with most context as long as content to parse is provided, but I'm glad my suggestion helped.

**Comment by noftaly** [comment]
Update: I tried to get the argument from the store, but it still requires [a context](https://sapphire-project.github.io/framework/interfaces/argumentcontext.html), which requires a command.
Maybe this issue should have been on the main repo, because it seems to require a refactor of the argument system, not the MessagePrompter 😄

**Comment by Nytelife26** [comment]
cc: @kyranet @Favna 

Thoughts and status on this? It seems to me that the best options are:
- Leave as it is
- Allow the parser context to be run with no command, since it technically doesn't need the command to parse things
